version: '3'
services:
  dbsql:
    image: mysql:8.0
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sentencecollector
      MYSQL_USER: admin
      MYSQL_PASSWORD: localdevelopment
      MYSQL_ROOT_PASSWORD: localdevelopment
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
